export const BASE_URL = ''
export const MENU_URL = '/api/menu'
export const USERS_URL = '/api/users'
export const ORDERS_URL = '/api/orders'
export const ADDRESS_URL = '/api/address'
export const PAYPAL_URL = '/api/config/paypal'
export const UPLOAD_URL = '/api/upload'